### ISSUE TITLE
Need Beta API ？

### ISSUE THREAD

**Issue by Yuchinsan** [oasoobi/noteblockplus#3]
はじめまして、ゆうちんと申します。
音ブロ技師をしており、統合版での作品を多く制作しておりますので
この機能にとても興奮しております！！

このたび、v1.21.41 にて noteblockplus を使用したところ
ベータAPI がOFFの設定の状態でもアドオンを使用できました。

最新版では不要になったのでしょうか？

**Comment by oasoobi** [comment]
Script APIのバージョンをalpha版にしたので、その影響かと思います。仕様変更がある可能性があるので、有効にしておくことを推奨します。

**Comment by Yuchinsan** [comment]
なるほど、そうなのですね？
わかりました！
ありがとうございます(^^)
